"""Add DeletedEmail table

Revision ID: 0dec1d73bb6b
Revises: 009_add_mock_datetime_support
Create Date: 2025-07-16 05:17:53.383126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dec1d73bb6b'
down_revision: Union[str, None] = '009_add_mock_datetime_support'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_emails_email'), 'deleted_emails', ['email'], unique=True)
    op.create_index(op.f('ix_deleted_emails_id'), 'deleted_emails', ['id'], unique=False)
    op.drop_table('goals_backup')
    op.drop_index(op.f('idx_goals_2week_completed_at'), table_name='goals_2_week')
    op.drop_index(op.f('idx_goals_2week_history_query'), table_name='goals_2_week')
    op.drop_index(op.f('idx_goals_2week_user_completed_at'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_duration'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_expires_at'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_goal_type'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_id'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_is_completed'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2week_name'), table_name='goals_2_week')
    op.create_index(op.f('ix_goals_2_week_duration'), 'goals_2_week', ['duration'], unique=False)
    op.create_index(op.f('ix_goals_2_week_expires_at'), 'goals_2_week', ['expires_at'], unique=False)
    op.create_index(op.f('ix_goals_2_week_goal_type'), 'goals_2_week', ['goal_type'], unique=False)
    op.create_index(op.f('ix_goals_2_week_id'), 'goals_2_week', ['id'], unique=False)
    op.create_index(op.f('ix_goals_2_week_is_completed'), 'goals_2_week', ['is_completed'], unique=False)
    op.create_index(op.f('ix_goals_2_week_name'), 'goals_2_week', ['name'], unique=False)
    op.drop_index(op.f('idx_goals_longterm_completed_at'), table_name='goals_long_term')
    op.drop_index(op.f('idx_goals_longterm_history_query'), table_name='goals_long_term')
    op.drop_index(op.f('idx_goals_longterm_user_completed_at'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_longterm_duration'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_longterm_goal_type'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_longterm_id'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_longterm_is_completed'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_longterm_name'), table_name='goals_long_term')
    op.create_index(op.f('ix_goals_long_term_duration'), 'goals_long_term', ['duration'], unique=False)
    op.create_index(op.f('ix_goals_long_term_goal_type'), 'goals_long_term', ['goal_type'], unique=False)
    op.create_index(op.f('ix_goals_long_term_id'), 'goals_long_term', ['id'], unique=False)
    op.create_index(op.f('ix_goals_long_term_is_completed'), 'goals_long_term', ['is_completed'], unique=False)
    op.create_index(op.f('ix_goals_long_term_name'), 'goals_long_term', ['name'], unique=False)
    op.drop_index(op.f('idx_users_mock_date_enabled'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_mock_date_enabled'), 'users', ['mock_date_enabled'], unique=False)
    op.drop_index(op.f('ix_goals_long_term_name'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_long_term_is_completed'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_long_term_id'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_long_term_goal_type'), table_name='goals_long_term')
    op.drop_index(op.f('ix_goals_long_term_duration'), table_name='goals_long_term')
    op.create_index(op.f('ix_goals_longterm_name'), 'goals_long_term', ['name'], unique=False)
    op.create_index(op.f('ix_goals_longterm_is_completed'), 'goals_long_term', ['is_completed'], unique=False)
    op.create_index(op.f('ix_goals_longterm_id'), 'goals_long_term', ['id'], unique=False)
    op.create_index(op.f('ix_goals_longterm_goal_type'), 'goals_long_term', ['goal_type'], unique=False)
    op.create_index(op.f('ix_goals_longterm_duration'), 'goals_long_term', ['duration'], unique=False)
    op.create_index(op.f('idx_goals_longterm_user_completed_at'), 'goals_long_term', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('idx_goals_longterm_history_query'), 'goals_long_term', ['user_id', 'completed_at', 'is_completed'], unique=False)
    op.create_index(op.f('idx_goals_longterm_completed_at'), 'goals_long_term', ['completed_at'], unique=False)
    op.drop_index(op.f('ix_goals_2_week_name'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2_week_is_completed'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2_week_id'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2_week_goal_type'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2_week_expires_at'), table_name='goals_2_week')
    op.drop_index(op.f('ix_goals_2_week_duration'), table_name='goals_2_week')
    op.create_index(op.f('ix_goals_2week_name'), 'goals_2_week', ['name'], unique=False)
    op.create_index(op.f('ix_goals_2week_is_completed'), 'goals_2_week', ['is_completed'], unique=False)
    op.create_index(op.f('ix_goals_2week_id'), 'goals_2_week', ['id'], unique=False)
    op.create_index(op.f('ix_goals_2week_goal_type'), 'goals_2_week', ['goal_type'], unique=False)
    op.create_index(op.f('ix_goals_2week_expires_at'), 'goals_2_week', ['expires_at'], unique=False)
    op.create_index(op.f('ix_goals_2week_duration'), 'goals_2_week', ['duration'], unique=False)
    op.create_index(op.f('idx_goals_2week_user_completed_at'), 'goals_2_week', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('idx_goals_2week_history_query'), 'goals_2_week', ['user_id', 'completed_at', 'is_completed'], unique=False)
    op.create_index(op.f('idx_goals_2week_completed_at'), 'goals_2_week', ['completed_at'], unique=False)
    op.create_table('goals_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_deleted_emails_id'), table_name='deleted_emails')
    op.drop_index(op.f('ix_deleted_emails_email'), table_name='deleted_emails')
    op.drop_table('deleted_emails')
    # ### end Alembic commands ### 