"""Initial database schema

Revision ID: 10497a25575c
Revises: 
Create Date: 2025-06-28 19:46:57.573309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10497a25575c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('timezone_detected_method', sa.String(), nullable=False),
    sa.Column('timezone_confidence', sa.Float(), nullable=False),
    sa.Column('timezone_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('calendar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_calendar_user_date')
    )
    op.create_index('idx_calendar_entries_locked', 'calendar_entries', ['is_locked'], unique=False)
    op.create_index('idx_calendar_entries_user_date', 'calendar_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_calendar_entries_date'), 'calendar_entries', ['date'], unique=False)
    op.create_index(op.f('ix_calendar_entries_id'), 'calendar_entries', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_entries_user_id'), 'calendar_entries', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_title'), 'goals', ['title'], unique=False)
    op.create_table('gratitude_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(text)) > 0 AND LENGTH(TRIM(text)) <= 500', name='chk_gratitude_text_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gratitude_date', 'gratitude_entries', ['date'], unique=False)
    op.create_index('idx_gratitude_user_date', 'gratitude_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_gratitude_entries_date'), 'gratitude_entries', ['date'], unique=False)
    op.create_index(op.f('ix_gratitude_entries_user_id'), 'gratitude_entries', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='chk_habit_name_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uix_user_habit_name')
    )
    op.create_index('idx_habits_user_active', 'habits', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_habits_user_favorite', 'habits', ['user_id', 'is_favorite'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('journal_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0 AND LENGTH(TRIM(name)) <= 100', name='chk_collection_name_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uix_user_collection_name')
    )
    op.create_index('idx_collections_user_id', 'journal_collections', ['user_id'], unique=False)
    op.create_index('idx_collections_user_private', 'journal_collections', ['user_id', 'is_private'], unique=False)
    op.create_index(op.f('ix_journal_collections_user_id'), 'journal_collections', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_table('mantras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantras_user_id'), 'mantras', ['user_id'], unique=False)
    op.create_table('mood_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('day_rating', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uix_user_entry_date')
    )
    op.create_index('idx_mood_entries_user_date', 'mood_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_mood_entries_entry_date'), 'mood_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_mood_entries_user_id'), 'mood_entries', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_id'), 'password_history', ['id'], unique=False)
    op.create_table('pomodoro_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('long_break_minutes', sa.Integer(), nullable=False),
    sa.Column('sessions_before_long', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_settings_user_id'), 'pomodoro_settings', ['user_id'], unique=True)
    op.create_table('quick_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_access_user_id'), 'quick_access', ['user_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_table('study_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sets_user_id'), 'study_sets', ['user_id'], unique=False)
    op.create_table('user_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('focus_time_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='user_date_unique')
    )
    op.create_index(op.f('ix_user_statistics_user_id'), 'user_statistics', ['user_id'], unique=False)
    op.create_table('calendar_habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('habit_name', sa.String(length=255), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_active_on_date', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_entry_id'], ['calendar_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_habit_completions_entry', 'calendar_habit_completions', ['calendar_entry_id'], unique=False)
    op.create_index('idx_calendar_habit_completions_habit', 'calendar_habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_calendar_entry_id'), 'calendar_habit_completions', ['calendar_entry_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_habit_id'), 'calendar_habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_id'), 'calendar_habit_completions', ['id'], unique=False)
    op.create_table('calendar_mood_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('day_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_entry_id'], ['calendar_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_mood_entries_entry', 'calendar_mood_entries', ['calendar_entry_id'], unique=False)
    op.create_index(op.f('ix_calendar_mood_entries_calendar_entry_id'), 'calendar_mood_entries', ['calendar_entry_id'], unique=True)
    op.create_index(op.f('ix_calendar_mood_entries_id'), 'calendar_mood_entries', ['id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['study_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_set_id'), 'flashcards', ['set_id'], unique=False)
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uix_habit_completion_date')
    )
    op.create_index('idx_habit_completions_habit', 'habit_completions', ['habit_id'], unique=False)
    op.create_index('idx_habit_completions_user_date', 'habit_completions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_habit_completions_date'), 'habit_completions', ['date'], unique=False)
    op.create_index(op.f('ix_habit_completions_habit_id'), 'habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_completions_user_id'), 'habit_completions', ['user_id'], unique=False)
    op.create_table('habit_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uix_habit_date')
    )
    op.create_index(op.f('ix_habit_streaks_date'), 'habit_streaks', ['date'], unique=False)
    op.create_index(op.f('ix_habit_streaks_habit_id'), 'habit_streaks', ['habit_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(title)) > 0 AND LENGTH(TRIM(title)) <= 200', name='chk_entry_title_length'),
    sa.CheckConstraint('LENGTH(content) <= 50000', name='chk_entry_content_length'),
    sa.ForeignKeyConstraint(['collection_id'], ['journal_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entries_collection_id', 'journal_entries', ['collection_id'], unique=False)
    op.create_index('idx_entries_created_at', 'journal_entries', ['created_at'], unique=False)
    op.create_index('idx_entries_updated_at', 'journal_entries', ['updated_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_collection_id'), 'journal_entries', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_collection_id'), table_name='journal_entries')
    op.drop_index('idx_entries_updated_at', table_name='journal_entries')
    op.drop_index('idx_entries_created_at', table_name='journal_entries')
    op.drop_index('idx_entries_collection_id', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_habit_streaks_habit_id'), table_name='habit_streaks')
    op.drop_index(op.f('ix_habit_streaks_date'), table_name='habit_streaks')
    op.drop_table('habit_streaks')
    op.drop_index(op.f('ix_habit_completions_user_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_habit_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_date'), table_name='habit_completions')
    op.drop_index('idx_habit_completions_user_date', table_name='habit_completions')
    op.drop_index('idx_habit_completions_habit', table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_index(op.f('ix_flashcards_set_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_calendar_mood_entries_id'), table_name='calendar_mood_entries')
    op.drop_index(op.f('ix_calendar_mood_entries_calendar_entry_id'), table_name='calendar_mood_entries')
    op.drop_index('idx_calendar_mood_entries_entry', table_name='calendar_mood_entries')
    op.drop_table('calendar_mood_entries')
    op.drop_index(op.f('ix_calendar_habit_completions_id'), table_name='calendar_habit_completions')
    op.drop_index(op.f('ix_calendar_habit_completions_habit_id'), table_name='calendar_habit_completions')
    op.drop_index(op.f('ix_calendar_habit_completions_calendar_entry_id'), table_name='calendar_habit_completions')
    op.drop_index('idx_calendar_habit_completions_habit', table_name='calendar_habit_completions')
    op.drop_index('idx_calendar_habit_completions_entry', table_name='calendar_habit_completions')
    op.drop_table('calendar_habit_completions')
    op.drop_index(op.f('ix_user_statistics_user_id'), table_name='user_statistics')
    op.drop_table('user_statistics')
    op.drop_index(op.f('ix_study_sets_user_id'), table_name='study_sets')
    op.drop_table('study_sets')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_quick_access_user_id'), table_name='quick_access')
    op.drop_table('quick_access')
    op.drop_index(op.f('ix_pomodoro_settings_user_id'), table_name='pomodoro_settings')
    op.drop_table('pomodoro_settings')
    op.drop_index(op.f('ix_password_history_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_mood_entries_user_id'), table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_entry_date'), table_name='mood_entries')
    op.drop_index('idx_mood_entries_user_date', table_name='mood_entries')
    op.drop_table('mood_entries')
    op.drop_index(op.f('ix_mantras_user_id'), table_name='mantras')
    op.drop_table('mantras')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_journal_collections_user_id'), table_name='journal_collections')
    op.drop_index('idx_collections_user_private', table_name='journal_collections')
    op.drop_index('idx_collections_user_id', table_name='journal_collections')
    op.drop_table('journal_collections')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index('idx_habits_user_favorite', table_name='habits')
    op.drop_index('idx_habits_user_active', table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_gratitude_entries_user_id'), table_name='gratitude_entries')
    op.drop_index(op.f('ix_gratitude_entries_date'), table_name='gratitude_entries')
    op.drop_index('idx_gratitude_user_date', table_name='gratitude_entries')
    op.drop_index('idx_gratitude_date', table_name='gratitude_entries')
    op.drop_table('gratitude_entries')
    op.drop_index(op.f('ix_goals_title'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_calendar_entries_user_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_date'), table_name='calendar_entries')
    op.drop_index('idx_calendar_entries_user_date', table_name='calendar_entries')
    op.drop_index('idx_calendar_entries_locked', table_name='calendar_entries')
    op.drop_table('calendar_entries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ### 