"""enhance journal models with security and gratitude

Revision ID: 1eec4e4473ec
Revises: dcfc4f5e564f
Create Date: 2025-06-24 19:16:10.219459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eec4e4473ec'
down_revision: Union[str, None] = 'dcfc4f5e564f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gratitude_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(text)) > 0 AND LENGTH(TRIM(text)) <= 500', name='chk_gratitude_text_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gratitude_date', 'gratitude_entries', ['date'], unique=False)
    op.create_index('idx_gratitude_user_date', 'gratitude_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_gratitude_entries_date'), 'gratitude_entries', ['date'], unique=False)
    op.create_index(op.f('ix_gratitude_entries_user_id'), 'gratitude_entries', ['user_id'], unique=False)
    op.add_column('journal_collections', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('journal_collections', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('journal_collections', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('journal_collections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('journal_collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('idx_collections_user_id', 'journal_collections', ['user_id'], unique=False)
    op.create_index('idx_collections_user_private', 'journal_collections', ['user_id', 'is_private'], unique=False)
    op.create_unique_constraint('uix_user_collection_name', 'journal_collections', ['user_id', 'name'])
    op.drop_column('journal_collections', 'title')
    op.add_column('journal_entries', sa.Column('is_encrypted', sa.Boolean(), nullable=False))
    op.add_column('journal_entries', sa.Column('encrypted_content', sa.Text(), nullable=True))
    op.alter_column('journal_entries', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('idx_entries_collection_id', 'journal_entries', ['collection_id'], unique=False)
    op.create_index('idx_entries_created_at', 'journal_entries', ['created_at'], unique=False)
    op.create_index('idx_entries_updated_at', 'journal_entries', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entries_updated_at', table_name='journal_entries')
    op.drop_index('idx_entries_created_at', table_name='journal_entries')
    op.drop_index('idx_entries_collection_id', table_name='journal_entries')
    op.alter_column('journal_entries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('journal_entries', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('journal_entries', 'encrypted_content')
    op.drop_column('journal_entries', 'is_encrypted')
    op.add_column('journal_collections', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_user_collection_name', 'journal_collections', type_='unique')
    op.drop_index('idx_collections_user_private', table_name='journal_collections')
    op.drop_index('idx_collections_user_id', table_name='journal_collections')
    op.alter_column('journal_collections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('journal_collections', 'updated_at')
    op.drop_column('journal_collections', 'password_hash')
    op.drop_column('journal_collections', 'is_private')
    op.drop_column('journal_collections', 'name')
    op.drop_index(op.f('ix_gratitude_entries_user_id'), table_name='gratitude_entries')
    op.drop_index(op.f('ix_gratitude_entries_date'), table_name='gratitude_entries')
    op.drop_index('idx_gratitude_user_date', table_name='gratitude_entries')
    op.drop_index('idx_gratitude_date', table_name='gratitude_entries')
    op.drop_table('gratitude_entries')
    # ### end Alembic commands ### 