"""add_is_active_to_habits

Revision ID: 336d54ba80d0
Revises: 6278236a7d6e
Create Date: 2025-06-22 19:06:30.838685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '336d54ba80d0'
down_revision: Union[str, None] = '6278236a7d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uix_habit_completion_date')
    )
    op.create_index('idx_habit_completions_habit', 'habit_completions', ['habit_id'], unique=False)
    op.create_index('idx_habit_completions_user_date', 'habit_completions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_habit_completions_date'), 'habit_completions', ['date'], unique=False)
    op.create_index(op.f('ix_habit_completions_habit_id'), 'habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_completions_user_id'), 'habit_completions', ['user_id'], unique=False)
    # Add is_active column with default value for existing rows
    op.add_column('habits', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE habits SET is_active = true WHERE is_active IS NULL")
    op.alter_column('habits', 'is_active', nullable=False)
    
    op.add_column('habits', sa.Column('last_updated_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('idx_habits_user_active', 'habits', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_habits_user_favorite', 'habits', ['user_id', 'is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_habits_user_favorite', table_name='habits')
    op.drop_index('idx_habits_user_active', table_name='habits')
    op.alter_column('habits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('habits', 'last_updated_utc')
    op.drop_column('habits', 'is_active')
    op.drop_index(op.f('ix_habit_completions_user_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_habit_id'), table_name='habit_completions')
    op.drop_index(op.f('ix_habit_completions_date'), table_name='habit_completions')
    op.drop_index('idx_habit_completions_user_date', table_name='habit_completions')
    op.drop_index('idx_habit_completions_habit', table_name='habit_completions')
    op.drop_table('habit_completions')
    # ### end Alembic commands ### 