"""Add habit is_favorite and mood multiple metrics

Revision ID: 3773df614cd2
Revises: 11a22ae8f8ab
Create Date: 2025-06-11 16:33:28.985519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3773df614cd2'
down_revision: Union[str, None] = '11a22ae8f8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uix_user_habit_name', 'habits', ['user_id', 'name'])
    op.add_column('mood_entries', sa.Column('happiness', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('satisfaction', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('stress', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('day_rating', sa.Integer(), nullable=False))
    op.drop_column('mood_entries', 'rating')
    op.drop_column('mood_entries', 'mood')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('mood', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mood_entries', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mood_entries', 'day_rating')
    op.drop_column('mood_entries', 'stress')
    op.drop_column('mood_entries', 'satisfaction')
    op.drop_column('mood_entries', 'happiness')
    op.drop_constraint('uix_user_habit_name', 'habits', type_='unique')
    op.drop_column('habits', 'is_favorite')
    # ### end Alembic commands ### 