"""Add Google OAuth fields to User model

Revision ID: 5ed366760dcb
Revises: 3773df614cd2
Create Date: 2025-06-11 19:19:14.497477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed366760dcb'
down_revision: Union[str, None] = '3773df614cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    
    # Add auth_provider as nullable first, then set default and make it NOT NULL
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE users SET auth_provider = 'local' WHERE auth_provider IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'auth_provider', nullable=False)
    
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ### 