"""Add user timezone support for global date time handling

Revision ID: 6278236a7d6e
Revises: e4a71160e85e
Create Date: 2025-06-21 21:38:49.210082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6278236a7d6e'
down_revision: Union[str, None] = 'e4a71160e85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_flashcard_set'), table_name='flashcards')
    op.drop_column('mood_entries', 'updated_at')
    op.drop_index(op.f('idx_studyset_title'), table_name='study_sets')
    op.drop_index(op.f('idx_studyset_user_created'), table_name='study_sets')
    op.alter_column('user_statistics', 'focus_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_statistics', 'completed_sessions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_statistics', 'completed_tasks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_user_statistics_user_id'), table_name='user_statistics')
    op.drop_constraint(op.f('user_statistics_user_id_date_key'), 'user_statistics', type_='unique')
    op.create_index(op.f('ix_user_statistics_user_id'), 'user_statistics', ['user_id'], unique=False)
    op.create_unique_constraint('user_date_unique', 'user_statistics', ['user_id', 'date'])
    # Add timezone columns with default values for existing users
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=False, server_default='UTC'))
    op.add_column('users', sa.Column('timezone_detected_method', sa.String(), nullable=False, server_default='auto'))
    op.add_column('users', sa.Column('timezone_confidence', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('users', sa.Column('timezone_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone_updated_at')
    op.drop_column('users', 'timezone_confidence')
    op.drop_column('users', 'timezone_detected_method')
    op.drop_column('users', 'timezone')
    op.drop_constraint('user_date_unique', 'user_statistics', type_='unique')
    op.drop_index(op.f('ix_user_statistics_user_id'), table_name='user_statistics')
    op.create_unique_constraint(op.f('user_statistics_user_id_date_key'), 'user_statistics', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_statistics_user_id'), 'user_statistics', ['user_id'], unique=False)
    op.alter_column('user_statistics', 'completed_tasks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_statistics', 'completed_sessions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_statistics', 'focus_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_studyset_user_created'), 'study_sets', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_studyset_title'), 'study_sets', ['title'], unique=False)
    op.add_column('mood_entries', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_flashcard_set'), 'flashcards', ['set_id'], unique=False)
    # ### end Alembic commands ### 