"""Update goals table structure

Revision ID: 99fc0ccab2e9
Revises: ab085f7c5503
Create Date: 2025-05-25 10:56:12.986038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99fc0ccab2e9'
down_revision: Union[str, None] = 'ab085f7c5503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('goals', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('goals', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('goals', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_goals_duration'), table_name='goals')
    op.drop_index(op.f('ix_goals_end_date'), table_name='goals')
    op.drop_index(op.f('ix_goals_start_date'), table_name='goals')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_title'), 'goals', ['title'], unique=False)
    op.drop_column('goals', 'start_date')
    op.drop_column('goals', 'end_date')
    op.drop_column('goals', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('duration', postgresql.ENUM('SHORT', 'LONG', name='goaldurationtype'), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_goals_title'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_goals_start_date'), 'goals', ['start_date'], unique=False)
    op.create_index(op.f('ix_goals_end_date'), 'goals', ['end_date'], unique=False)
    op.create_index(op.f('ix_goals_duration'), 'goals', ['duration'], unique=False)
    op.drop_column('goals', 'updated_at')
    op.drop_column('goals', 'category')
    op.drop_column('goals', 'priority')
    op.drop_column('goals', 'is_completed')
    op.drop_column('goals', 'target_date')
    # ### end Alembic commands ### 