"""add calendar implementation

Revision ID: dcfc4f5e564f
Revises: 942cfdd600e1
Create Date: 2025-06-23 17:35:13.934950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfc4f5e564f'
down_revision: Union[str, None] = '942cfdd600e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_calendar_user_date')
    )
    op.create_index('idx_calendar_entries_locked', 'calendar_entries', ['is_locked'], unique=False)
    op.create_index('idx_calendar_entries_user_date', 'calendar_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_calendar_entries_date'), 'calendar_entries', ['date'], unique=False)
    op.create_index(op.f('ix_calendar_entries_id'), 'calendar_entries', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_entries_user_id'), 'calendar_entries', ['user_id'], unique=False)
    op.create_table('calendar_habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('habit_name', sa.String(length=255), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_active_on_date', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_entry_id'], ['calendar_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_habit_completions_entry', 'calendar_habit_completions', ['calendar_entry_id'], unique=False)
    op.create_index('idx_calendar_habit_completions_habit', 'calendar_habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_calendar_entry_id'), 'calendar_habit_completions', ['calendar_entry_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_habit_id'), 'calendar_habit_completions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_calendar_habit_completions_id'), 'calendar_habit_completions', ['id'], unique=False)
    op.create_table('calendar_mood_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('day_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_entry_id'], ['calendar_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_mood_entries_entry', 'calendar_mood_entries', ['calendar_entry_id'], unique=False)
    op.create_index(op.f('ix_calendar_mood_entries_calendar_entry_id'), 'calendar_mood_entries', ['calendar_entry_id'], unique=True)
    op.create_index(op.f('ix_calendar_mood_entries_id'), 'calendar_mood_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_mood_entries_id'), table_name='calendar_mood_entries')
    op.drop_index(op.f('ix_calendar_mood_entries_calendar_entry_id'), table_name='calendar_mood_entries')
    op.drop_index('idx_calendar_mood_entries_entry', table_name='calendar_mood_entries')
    op.drop_table('calendar_mood_entries')
    op.drop_index(op.f('ix_calendar_habit_completions_id'), table_name='calendar_habit_completions')
    op.drop_index(op.f('ix_calendar_habit_completions_habit_id'), table_name='calendar_habit_completions')
    op.drop_index(op.f('ix_calendar_habit_completions_calendar_entry_id'), table_name='calendar_habit_completions')
    op.drop_index('idx_calendar_habit_completions_habit', table_name='calendar_habit_completions')
    op.drop_index('idx_calendar_habit_completions_entry', table_name='calendar_habit_completions')
    op.drop_table('calendar_habit_completions')
    op.drop_index(op.f('ix_calendar_entries_user_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_date'), table_name='calendar_entries')
    op.drop_index('idx_calendar_entries_user_date', table_name='calendar_entries')
    op.drop_index('idx_calendar_entries_locked', table_name='calendar_entries')
    op.drop_table('calendar_entries')
    # ### end Alembic commands ### 